# Generated by Django 4.2.4 on 2023-08-25 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friend_set",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Friends"
            ),
        ),
    ]
