# Generated by Django 4.2.4 on 2023-08-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_user_friend_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(blank=True, max_length=191, verbose_name="Status"),
        ),
    ]
