# Generated by Django 4.2.4 on 2023-08-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True, max_length=191, null=True, verbose_name="Status"
            ),
        ),
    ]
