# Generated by Django 4.2.4 on 2023-08-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="avatar",
            field=models.ImageField(
                null=True,
                upload_to="room_avatar/%Y-%m-%d-%H-%M-%S/",
                verbose_name="Avatar",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="title",
            field=models.CharField(
                default="Беседа", max_length=191, verbose_name="Title"
            ),
        ),
    ]
